definitions:
  schemas.Chat:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  schemas.ChatToCreate:
    properties:
      name:
        type: string
    type: object
  schemas.ChatUserToCreate:
    properties:
      chat_id:
        type: integer
      from_id:
        type: integer
    type: object
  schemas.HTTPError:
    properties:
      message: {}
    type: object
  schemas.Message:
    properties:
      chat_id:
        type: integer
      created_at:
        type: string
      from_id:
        type: integer
      id:
        type: integer
      text:
        type: string
    required:
    - chat_id
    - from_id
    - text
    type: object
  schemas.MessageToCreate:
    properties:
      chat_id:
        type: integer
      from_id:
        type: integer
      text:
        type: string
    required:
    - chat_id
    - from_id
    - text
    type: object
  schemas.Messages:
    properties:
      messages:
        items:
          $ref: '#/definitions/schemas.Message'
        type: array
    type: object
  schemas.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      firstname:
        type: string
      id:
        type: integer
      lastname:
        type: string
      username:
        type: string
    required:
    - firstname
    - lastname
    - username
    type: object
  schemas.UserToCreate:
    properties:
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - firstname
    - password
    - username
    type: object
  schemas.UserToUpdate:
    properties:
      email:
        type: string
      firstname:
        type: string
      id:
        type: integer
      lastname:
        type: string
      username:
        type: string
    required:
    - firstname
    - username
    type: object
  schemas.Users:
    properties:
      users:
        items:
          $ref: '#/definitions/schemas.User'
        type: array
    type: object
host: localhost:1323
info:
  contact:
    email: support@worki.io
    name: Worki Support
  description: This is API for Worki Messanger.
  title: Worki messenger API
  version: "0.1"
paths:
  /chats/:
    post:
      consumes:
      - application/json
      parameters:
      - description: Add User to Chat data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.ChatUserToCreate'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.HTTPError'
      summary: Add user to chat
  /chats/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Chat ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.HTTPError'
      summary: Delete chat by ID
  /chats/msg/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Chat ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.Messages'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.HTTPError'
      summary: Get chat messages
  /messages/:
    get:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.Messages'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.HTTPError'
      summary: Get messages
    post:
      consumes:
      - application/json
      parameters:
      - description: Message data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.MessageToCreate'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/schemas.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.HTTPError'
      summary: Create message
  /messages/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Message ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/schemas.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.HTTPError'
      summary: Delete message by ID
  /users/:
    get:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.Users'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.HTTPError'
      summary: Get users
    post:
      consumes:
      - application/json
      parameters:
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.UserToCreate'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/schemas.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.HTTPError'
      summary: Create user
  /users/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.HTTPError'
      summary: Delete user by ID
    get:
      consumes:
      - application/json
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.User'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.HTTPError'
      summary: Get user by ID
    put:
      consumes:
      - application/json
      parameters:
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.UserToUpdate'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/schemas.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.HTTPError'
      summary: Update user
  /users/usr/{username}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Account Username
        in: path
        name: username
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.HTTPError'
      summary: Delete user by Username
    get:
      consumes:
      - application/json
      parameters:
      - description: Username
        in: path
        name: username
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.User'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.HTTPError'
      summary: Get user by Username
swagger: "2.0"
